<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">C++用户定义异常</h1><div style="width:100%;float:left;" class="article-content">   
 <p>C++中不存在的新异常，可以通过重写和继承异常类功能来定义。</p> 
 <h2 id="h2-c-"><a name="C++用户定义的异常示例" class="reference-link"></a><span class="header-link octicon octicon-link"></span>C++用户定义的异常示例</h2>
 <p>下面来看看看用户定义的异常的简单例子，其中使用<code>std::exception</code>类来定义异常。</p> 
 <pre><code class="lang-cpp">#include &lt;iostream&gt;  
#include &lt;exception&gt;  
using namespace std;  
class MyException : public exception{  
    public:  
        const char * what() const throw()  
        {  
            return "Attempted to divide by zero!\n";  
        }  
};  
int main()  
{  
    try  
    {  
        int x, y;  
        cout &lt;&lt; "Enter the two numbers : \n";  
        cin &gt;&gt; x &gt;&gt; y;  
        if (y == 0)  
        {  
            MyException z;  
            throw z;  
        }  
        else  
        {  
            cout &lt;&lt; "x / y = " &lt;&lt; x/y &lt;&lt; endl;  
        }  
    }  
    catch(exception&amp; e)  
    {  
        cout &lt;&lt; e.what();  
    }
    return 0;
}
</code></pre> 
 <p>上面代码执行输出结果如下 -</p>   
 <pre><code class="lang-cpp">Enter the two numbers :
10
2
x / y = 5
</code></pre> 
 <p>上面代码执行一个除<code>0</code>异常，输出结果如下 -</p> 
 <pre><code class="lang-cpp">Enter the two numbers :
10
0
Attempted to divide by zero!
</code></pre> 
 <blockquote> 
  <p>注意：在上面的例子中，<code>what()</code>是一个由 <code>exception</code> 类提供的公共方法。 它用于返回异常的原因。</p> 
 </blockquote>
 <br>      
</div></body></html>