<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">Python3异常处理</h1><div style="width:100%;float:left;" class="article-content">   
 <div> 
  <div>
    Python提供了两个非常重要的功能，以处理任何意外错误在你的Python程序，并在它们上面添加了调试功能 - 
  </div> 
 </div> 
 <div> 
  <ul> 
   <li> <p style="text-align:justify;"> 异常处理:&nbsp;这将在本教程所覆盖讲解。这是 Python 提供的标准异常的列表：<a target="_blank" href="http://www.yiibai.com/python3/standard_exceptions.html">标准异常</a> </p> </li> 
   <li> <p style="text-align:justify;"> 断言:&nbsp;这将在<a target="_blank" href="http://www.yiibai.com/python3/assertions_in_python.html">&nbsp;Python3断言</a>教程覆盖。 </p> </li> 
  </ul> 
  <div>
    标准异常如下列表&nbsp;- 
  </div> 
  <table border="1" cellpadding="2" cellspacing="0" style="font-size:14px;color:#313131;font-family:Verdana, Geneva, Tahoma,  Helvetica, background-color:inherit;"> 
   <tbody> 
    <tr> 
     <th style="border:1px solid #999999;background-color:#EEEEEE;"> 
      <div style="background-color:inherit;">
        异常名称 
      </div> </th> 
     <th style="border:1px solid #999999;background-color:#EEEEEE;"> <b>描述</b> </th> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> Exception </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        所有异常的基类 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> StopIteration </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当一个迭代器的&nbsp;next()方法不指向任何对象时引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> SystemExit </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        由 sys.exit()函数引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> StandardError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        除了StopIteration异常和SystemExit，所有内置异常的基类 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> ArithmeticError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        数值计算所发生的所有错误的基类 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> OverflowError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当数字类型
       <span style="font-family:Verdana, Geneva, Tahoma,  Helvetica, font-size:14px;">计算超过最高限额</span>引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> FloatingPointError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当一个浮点运算失败时触发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> ZeroDivisonError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当除运算或模零在所有数值类型运算时引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> AssertionError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        断言语句失败的情况下引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> AttributeError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        属性引用或赋值失败的情况下引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> EOFError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当从&nbsp;raw_input()&nbsp;与&nbsp;input()&nbsp;函数输入，到达文件末尾时触发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> ImportError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当一个 import 语句失败时触发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> KeyboardInterrupt </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当用户中断程序执行，通常是通过按 Ctrl+c 引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> LookupError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        所有查找错误基类 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> IndexError </p> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> KeyError </p> </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当在一个序列中没有找到一个索引时引发 
      </div> 
      <div style="background-color:inherit;">
        当指定的键没有在字典中找到引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> NameError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当在局部或全局命名空间中找不到的标识引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> UnboundLocalError </p> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> EnvironmentError </p> </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        试图访问在函数或方法的局部变量时引发，但没有值分配给它。 
      </div> 
      <div style="background-color:inherit;">
        Python环境之外发生的所有异常的基类。 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> IOError </p> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> IOError </p> </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当一个输入/输出操作失败，如打印语句或 open()函数试图打开不存在的文件时
       <span style="font-family:Verdana, Geneva, Tahoma,  Helvetica, font-size:14px;">引发</span> 
      </div> 
      <div style="background-color:inherit;">
        操作系统相关的错误时引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> SyntaxError </p> <p style="color:#000000;text-align:justify;font-size:15px !important;background-color:inherit;"> IndentationError </p> </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当在Python语法错误引发；
       <br> 
       <span style="background-color:inherit;font-size:inherit;line-height:1.5;">没有正确指定缩进引发。</span> 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> SystemError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当解释器发现一个内部问题，但遇到此错误时，Python解释器不退出引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> SystemExit </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> <span style="background-color:inherit;font-size:inherit;line-height:1.5;">当Python解释器不使用sys.exit()函数引发。</span><span style="background-color:inherit;font-size:inherit;line-height:1.5;">如果代码没有被处理，解释器会退出。</span> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> <br> </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当操作或函数在指定数据类型无效时引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> ValueError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> <span style="background-color:inherit;font-size:inherit;line-height:1.5;">在内置函数对于数据类型，参数的有效类型时引发，</span><span style="background-color:inherit;font-size:inherit;line-height:1.5;">但是参数指定了无效值</span> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> RuntimeError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当生成的错误不属于任何类别时引发 
      </div> </td> 
    </tr> 
    <tr> 
     <td style="border:1px solid #999999;background-color:inherit;"> NotImplementedError </td> 
     <td style="border:1px solid #999999;background-color:inherit;"> 
      <div style="background-color:inherit;">
        当要在继承的类来实现，抽象方法实际上没有实现时引发此异常 
      </div> </td> 
    </tr> 
   </tbody> 
  </table> 
  <h3> 
   <div>
     在Python中断言 
   </div> </h3> 
  <div>
    断言是一种理智检查，当程序的测试完成，你可以打开或关闭。 
  </div> 
  <p style="text-align:justify;"> 断言的最简单的方法就是把它比作&nbsp;raise-if&nbsp;语句&nbsp;(或者更准确，加 raise-if-not&nbsp;声明).&nbsp;一个表达式进行测试，如果结果出现&nbsp;false，将引发异常。 </p> 
  <div>
    断言是由&nbsp;assert&nbsp;语句，在Python中新的关键字，在Python1.5版本中引入使用的关键字。 
  </div> 
  <div>
    程序员常常放置断言来检查输入的有效，或在一个函数调用后检查有效的输出。 
  </div> 
  <h3> assert&nbsp;语句 </h3> 
  <p style="text-align:justify;"> 当它遇到一个断言语句，Python评估计算之后的表达式，希望是&nbsp;true&nbsp;值。如果表达式为 false，Python 触发 AssertionError 异常。 </p> 
  <div>
    断言的语法是&nbsp;- 
  </div> 
  <pre>assert Expression[, Arguments]&nbsp;</pre> 
  <p style="text-align:justify;"> 如果断言失败，Python使用&nbsp;ArgumentExpression&nbsp;作为AssertionError异常的参数。AssertionError异常可以被捕获，并用 try-except语句处理类似其他异常，但是，如果没有处理它们将终止该程序并产生一个回溯。 </p> 
  <h3> 示例 </h3> 
  <p style="text-align:justify;"> 这里是一个把从开氏度到华氏度的温度转换函数。 </p> 
  <pre>#!/usr/bin/python3
def KelvinToFahrenheit(Temperature):
    assert (Temperature &gt;= 0),"Colder than absolute zero!"
    return ((Temperature-273)*1.8)+32

print (KelvinToFahrenheit(273))
print (int(KelvinToFahrenheit(505.78)))
print (KelvinToFahrenheit(-5))</pre> 
  <div>
    当执行上面的代码，它产生以下结果&nbsp;- 
  </div> 
  <pre>32.0
451
Traceback (most recent call last):
File "test.py", line 9, in 
print KelvinToFahrenheit(-5)
File "test.py", line 4, in KelvinToFahrenheit
assert (Temperature &gt;= 0),"Colder than absolute zero!"
AssertionError: Colder than absolute zero!</pre> 
  <h2> 
   <div>
     什么是异常？ 
   </div> </h2> 
  <p style="text-align:justify;"> 异常是一个事件，这在程序的执行过程中扰乱程序的指令的正常流程。一般来说，当一个 Python 脚本遇到一种情况，它无法应付则会引发一个异常。异常它是一个 Python 对象，它表示一个错误。 </p> 
  <div>
    当&nbsp;Python&nbsp;脚本会引发一个异常，它必须要么处理异常，要么终止并退出。 
  </div> 
  <h2> 
   <div>
     处理异常 
   </div> </h2> 
  <p style="text-align:justify;"> 如果你有一些可疑的代码，可能会引发异常，&nbsp;可以通过将可疑代码放在一个&nbsp;try:&nbsp;块来保护你的程序。在&nbsp;try：块之后，包括&nbsp;except:&nbsp;语句随后的代码块，作为优雅的处理异常问题。 </p> 
  <h3> 语法 </h3> 
  <p style="text-align:justify;"> 下面是&nbsp;try....except...else&nbsp;块的简单的语法&nbsp;− </p>   
  <pre>try:
   You do your operations here
   ......................
except <i>ExceptionI</i>:
   If there is ExceptionI, then execute this block.
except <i>ExceptionII</i>:
   If there is ExceptionII, then execute this block.
   ......................
else:
   If there is no exception then execute this block. </pre> 
  <div>
    以下是有关上述语法几个重要的地方 - 
  </div> 
  <ul> 
   <li> <p style="text-align:justify;"> 单个 try 语句可以有多个except语句。&nbsp;当 try 块包含可能抛出不同类型的异常声明这是有用的 </p> </li> 
   <li> 
    <div>
      也可以提供一个通用的&nbsp;except&nbsp;子句来处理任何异常 
    </div> </li> 
   <li> <p style="text-align:justify;"> except子句后，可以包括&nbsp;else&nbsp;子句。&nbsp;如果代码在try：块不引发异常则代码在&nbsp;else&nbsp;块执行 </p> </li> 
   <li> 
    <div>
      else&nbsp;块是代码的好地方，这不需要&nbsp;try:&nbsp;块的保护 
    </div> </li> 
  </ul> 
  <h3> 示例 </h3> 
  <div>
    这个例子打开一个文件，并写入内容，文件处理完全没有问题 - 
  </div> 
  <pre>#!/usr/bin/python3

try:
   fh = open("testfile", "w")
   fh.write("This is my test file for exception handling!!")
except IOError:
   print ("Error: can\'t find file or read data")
else:
   print ("Written content in the file successfully")
   fh.close()
</pre> 
  <div>
    这将产生以下结果&nbsp;- 
  </div> 
  <pre>Written content in the file successfully</pre> 
  <h3> 示例 </h3> 
  <div>
    这个例子试图打开一个文件，如果没有写权限，它会抛出一个异常 - 
  </div> 
  <pre>#!/usr/bin/python3

try:
   fh = open("testfile", "r")
   fh.write("This is my test file for exception handling!!")
except IOError:
   print ("Error: can\'t find file or read data")
else:
   print ("Written content in the file successfully")</pre> 
  <div style="background-color:inherit;">
    这将产生以下结果&nbsp;- 
  </div> 
  <pre>Error: can't find file or read data</pre> 
  <h2> 
   <div>
     except子句中无异常 
   </div> </h2> 
  <div>
    也可以使用&nbsp;except&nbsp;语句定义如下无异常声明如下&nbsp;- 
  </div> 
  <pre>try:
   You do your operations here
   ......................
except:
   If there is any exception, then execute this block.
   ......................
else:
   If there is no exception then execute this block. </pre> 
  <h2> 
   <div>
     except子句与多个异常 
   </div> </h2> 
  <div>
    也可以使用相同的 except 语句来处理多个异常，具体如下&nbsp;- 
  </div> 
  <pre>try:
   You do your operations here
   ......................
except(Exception1[, Exception2[,...ExceptionN]]]):
   If there is any exception from the given exception list, 
   then execute this block.
   ......................
else:
   If there is no exception then execute this block. </pre> 
  <h2> try-finally子句 </h2> 
  <p style="text-align:justify;"> 可以使用&nbsp;finally:&nbsp;使用&nbsp;try:&nbsp;块.&nbsp;finally 块是必须执行，而不管 try 块是否引发异常或没有。try-finally 语句的语法是这样的&nbsp;- </p> 
  <pre>try:
   You do your operations here;
   ......................
   Due to any exception, this may be skipped.
finally:
   This would always be executed.
   ......................&nbsp;</pre> 
  <p style="text-align:justify;"> 请注意，可以提供&nbsp;except 子句，或 finally 子句，但不能同时使用。不能用一个 finally 子句中再使用 else 子句 。 </p> 
  <h3> 示例 </h3> 
  <pre>#!/usr/bin/python3

try:
   fh = open("testfile", "w")
   fh.write("This is my test file for exception handling!!")
finally:
   print ("Error: can\'t find file or read data")
   fh.close()</pre> 
  <div style="background-color:inherit;">
    如果您没有以写入方式打开文件的权限，那么这将产生以下结果： 
  </div> 
  <pre>Error: can't find file or read data</pre> 
  <div style="background-color:inherit;">
    同样的例子可以更清晰地写成如下&nbsp;- 
  </div> 
  <pre>#!/usr/bin/python3

try:
   fh = open("testfile", "w")
   try:
      fh.write("This is my test file for exception handling!!")
   finally:
      print ("Going to close the file")
      fh.close()
except IOError:
   print ("Error: can\'t find file or read data")&nbsp;</pre> 
  <p style="text-align:justify;"> 当一个异常在try块被抛出，立即执行传递给 finally 块。如果在 try-except 语句的下一个更高的层异常被再次引发，并在处理&nbsp;except&nbsp;语句外。 </p> 
  <h2> 
   <div>
     异常的参数 
   </div> </h2> 
  <p style="text-align:justify;"> 异常可以有一个参数，这是有关问题的其他信息的值。参数的内容作为异常而都不太一样。可以通过不同的子句中提供一个变量，如下所示捕获异常参数&nbsp;- </p> 
  <pre>try:
   You do your operations here
   ......................
except <i>ExceptionType as Argument</i>:
   You can print value of Argument here...&nbsp;</pre> 
  <p style="text-align:justify;"> 如果写代码来处理一个异常，可以使用一个变量按照异常的名称在&nbsp;except&nbsp;语句中。&nbsp;如果要捕捉多个异常，可以使用一个变量后跟一个异常的元组。 </p> 
  <p style="text-align:justify;"> 该变量接收大多含有异常的原因各种值。变量可以在一个元组的形式以接收一个或多个值。这个元组通常包含错误字符串，错误编号，以及错误位置。 </p> 
  <h3> 示例 </h3> 
  <div>
    下面是一个异常的例子- 
  </div> 
  <pre>#!/usr/bin/python3

# Define a function here.
def temp_convert(var):
   try:
      return int(var)
   except ValueError, as Argument:
      print ("The argument does not contain numbers\n", Argument)

# Call above function here.
temp_convert("xyz")</pre> 
  <div style="background-color:inherit;">
    这将产生以下结果&nbsp;- 
  </div> 
  <pre>The argument does not contain numbers
invalid literal for int() with base 10: 'xyz'</pre> 
  <h2> 
   <div>
     引发异常 
   </div> </h2> 
  <p style="text-align:justify;"> 可以通过使用&nbsp;raise&nbsp;语句触发几个方面的异常。对于 raise 语句的一般语法如下。 </p> 
  <h3> 语法 </h3> 
  <pre>raise [Exception [, args [, traceback]]]</pre> 
  <div>
    这里，Exception&nbsp;是异常的类型(例如，NameError)argument&nbsp;为异常的参数值。该参数是可选的;如果没有提供，异常的参数是None。 
  </div> 
  <div>
    最后一个参数&nbsp;traceback，也可选的(并在实践中很少使用)，并且如果存在的话，是用于异常的回溯对象。 
  </div> 
  <h3> 示例 </h3> 
  <p style="text-align:justify;"> 异常可以是一个字符串，一个类或一个对象。大多数Python的异常核心是触发类异常，使用类的一个实例参数的异常。定义新的异常是很容易的，可以按如下做法 &nbsp;- </p> 
  <pre>def functionName( level ):
    if level &lt;1:
        raise Exception(level)
        # The code below to this would not be executed
        # if we raise the exception
    return level&nbsp;</pre> 
  <p style="text-align:justify;"> 注意：为了捕捉异常，一个“except”语句必须是指出抛出类对象异常或简单的字符串异常。例如，捕获异常上面，我们必须编写&nbsp;except&nbsp;子句如下 - </p> 
  <pre>try:
   Business Logic here...
except Exception as e:
   Exception handling here using e.args...
else:
   Rest of the code here...</pre> 
  <div style="background-color:inherit;">
    下面的例子说明如何使用触发异常： 
  </div> 
  <pre>#!/usr/bin/python3
def functionName( level ):
    if level &lt;1:
        raise Exception(level)
        # The code below to this would not be executed
        # if we raise the exception
    return level

try:
    l=functionName(-10)
    print ("level=",l)
except Exception as e:
    print ("error in level argument",e.args[0])</pre> 
  <div style="background-color:inherit;">
    这将产生以下结果 
  </div> 
  <pre>error in level argument -10</pre> 
  <h2> 
   <div>
     用户定义的异常 
   </div> </h2> 
  <div>
    Python中，还可以通过内置的异常标准的派生类来创建自己的异常。 
  </div> 
  <p style="text-align:justify;"> 这里是关于 RuntimeError 的一个例子。这里一个类被创建，它是 RuntimeError 的子类。当需要时，一个异常可以捕获用来显示更具体的信息，这非常有用。 </p> 
  <p style="text-align:justify;"> 在try块，用户定义的异常将引发，并夹在 except 块中。&nbsp;变量e是用来创建网络错误&nbsp;Networkerror&nbsp;类的实例。 </p> 
  <pre>class Networkerror(RuntimeError):
   def __init__(self, arg):
      self.args = arg</pre> 
  <div style="background-color:inherit;">
    所以上面的类定义后，可以引发异常如下&nbsp;- 
  </div> 
  <pre>try:
   raise Networkerror("Bad hostname")
except Networkerror,e:
   print e.args</pre> 
 </div>
 <br>      
</div></body></html>