<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">JavaScript错误和异常处理</h1><div style="width:100%;float:left;" class="article-content">   
 <p> 有三种类型的编程错误：(1)语法错误和(2)运行时错误(3)逻辑错误：</p> 
 <h1> 语法错误：</h1> 
 <p> 语法错误，也被称为解析错误，在编译时进行传统的编程语言，并出现在JavaScript解释时。</p> 
 <p> 例如，下面一行将导致一个语法错误，因为它缺少一个右括号：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;script type="text/javascript"&gt;
&lt;!--
window.print(;
//--&gt;
&lt;/script&gt;</pre> 
 <p> 当一个语法错误在JavaScript中出现，只有在同一个线程中包含的语法错误的影响，在其他线程的代码被执行；代码依赖于包含错误的代码不会被执行。</p> 
 <h1> 运行时错误：</h1> 
 <p> 执行(编译/解释后)在运行时错误，也被称为异常，会引发。</p> 
 <p> 例如，下面一行将导致运行时错误，因为这里的语法是正确的，但在运行时它正试图调用非存在的方法：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;script type="text/javascript"&gt;
&lt;!--
window.printme();
//--&gt;
&lt;/script&gt;</pre> 
 <p> 例外情况也影响到它们发生的线程，允许其他JavaScript线程继续正常执行。</p> 
 <h1> 逻辑错误：</h1> 
 <p> 逻辑错误可能是最困难的类型的错误跟踪。这些错误是不是一个语法或运行时错误的结果。相反，当发生一个错误的驱动脚本逻辑，你没有得到所期望的结果。</p> 
 <p> 你可能无法抓到这些错误，因为这取决于程序是什么类型的逻辑是基于业务需求。</p> 
 <h1> try...catch...finally&nbsp;语句:</h1> 
 <p> JavaScript的最新版本中添加的异常处理能力。JavaScript实现 try ... catch... finally结构以及抛出操作来处理异常。</p> 
 <p> 你可以捕获程序员生成和运行时异常，但不能捕获JavaScript语法错误。</p> 
 <p> 这里是&nbsp;try...catch...finally&nbsp;块语法：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;script type="text/javascript"&gt;
&lt;!--
try {
    // Code to run
    [break;]
} catch ( e ) {
    // Code to run if an exception occurs
    [break;]
}[ finally {
    // Code that is always executed regardless of 
    // an exception occurring
}]
//--&gt;
&lt;/script&gt;</pre> 
 <p> try块必须后跟只有一个catch块或者一个finally块（或两者之一）。当一个异常在try块时，除被放置在e和catch块被执行。 try/catch语句后的可选finally块无条件地执行。</p> 
 <h2> 示例:</h2> 
 <p> 下面是一个例子，我们正试图调用一个不存在的函数，这将引发异常。让我们来看看它的行为，不具有try ... catch：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
function myFunc()
{
   var a = 100;

   alert("Value of variable a is : " + a );
 
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> 现在，让我们尝试使用 try ... catch 捕获这个异常，并显示一个用户友好的消息。也可以取消此消息，如果要隐藏从用户这个错误。</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
function myFunc()
{
   var a = 100;
   
   try {
      alert("Value of variable a is : " + a );
   } catch ( e ) {
      alert("Error: " + e.description );
   }
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> 可以使用finally块将永远try/catch语句后，无条件地执行。下面是一个例子：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
function myFunc()
{
   var a = 100;
   
   try {
      alert("Value of variable a is : " + a );
   }catch ( e ) {
      alert("Error: " + e.description );
   }finally {
      alert("Finally block will always execute!" );
   }
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> throw&nbsp;语句:</p> 
 <p> 可以使用throw语句来提高你的内置异常或自定义异常。后来这些异常可以被捕获并可以采取适当的行动。</p> 
 <p> 以下是表示throw语句的用法的例子。</p>   
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
function myFunc()
{
   var a = 100;
   var b = 0;
   
   try{
      if ( b == 0 ){
         throw( "Divide by zero error." ); 
      }else{
         var c = a / b;
      }
   }catch ( e ) {
      alert("Error: " + e );
   }
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> 您可以使用字符串，整数，布尔或对象在一个函数抛出一个异常，那么可以捕捉例外在相同的函数，我们在上面做了，或者使用try ... catch块在其他的函数。</p> 
 <h1> onerror()&nbsp;语法</h1> 
 <p> onerror事件处理程序是第一个特点，方便JavaScript处理错误。错误事件被触发窗口对象，每当一个异常页面上出现。例如：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
window.onerror = function () {
   alert("An error occurred.");
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> onerror事件处理程序提供了三条信息，以找出错误的确切性质：</p> 
 <ul> 
  <li> <p> 错误消息 . 浏览器将显示给定的错误相同的消息</p> </li> 
  <li> <p> URL&nbsp;. 在发生错误的文件</p> </li> 
  <li> <p> 行号. 在导致错误的URL给出的行号</p> </li> 
 </ul> 
 <p> 这里是例子来说明如何提取此信息</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;html&gt;
&lt;head&gt;
&lt;script type="text/javascript"&gt;
&lt;!--
window.onerror = function (msg, url, line) {
   alert("Message : " + msg );
   alert("url : " + url );
   alert("Line number : " + line );
}
//--&gt;
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click the following to see the result:&lt;/p&gt;
&lt;form&gt;
&lt;input type="button" value="Click Me" onclick="myFunc();" /&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;</pre> 
 <p> 可以显示在任何方式，你觉得这是更好的提取信息。</p> 
 <p> 可以使用onError方法来显示错误消息的情况下没有在如下加载图像的任何问题：</p> 
 <pre style="'Courier New', monospace; font-size: 12px; ">
&lt;img src="myimage.gif"
    onerror="alert('An error occurred loading the image.')" /&gt;</pre> 
 <p> 可以使用的onerror许多HTML标记错误的情况下显示相应的信息。</p> 
 <br>      
</div></body></html>